channels:
  # Define conda channels here. 
  - defaults
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python

  - pip
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework

